# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'

includes:
  json: https://raw.githubusercontent.com/Terradue/taskfile-utils/refs/heads/main/json.yaml
  quality: https://raw.githubusercontent.com/Terradue/taskfile-utils/refs/heads/main/quality.yaml

tasks:

  datamodel_codegen:
    cmds:
    - task: json:create_models
      vars:
        SCHEMA: './schemas/osc_ogcapi_records_models.yaml'
        BASE_CLASS: 'transpiler_mate.ogcapi.records.ogcapi_records_models.RecordCommonProperties'
        OUTPUT: './src/osc_client/models.py'

  bundle_worflow:
    internal: true
    cmds:
    - |
      uv run \
      --no-cache \
      --no-project \
      --with cwl-loader \
      cwl-loader bundle \
      ./cwl-workflows/{{.WORKFLOW_ID}}.cwl \
      --output ./cwl-workflows/{{.WORKFLOW_ID}}_bundled.cwl

  generate_workflow_doc:
    internal: true
    vars:
      DOC_DIR: './docs/c4/components/workflow'
      REPO_URL:
        sh: git config --get remote.origin.url
    cmds:
    - task: bundle_worflow
      vars:
        WORKFLOW_ID: "{{.WORKFLOW_ID}}"
    - mkdir -p {{.DOC_DIR}}
    - |
      uv run \
      --no-cache \
      --no-project \
      --with cwltool \
      cwltool --validate ./cwl-workflows/{{.WORKFLOW_ID}}_bundled.cwl
    - |
      uv run --no-cache --no-project --with transpiler-mate transpiler-mate markdown \
        --workflow-id {{.WORKFLOW_ID}} \
        --output {{.DOC_DIR}} \
        --code-repository {{.REPO_URL}} \
        ./cwl-workflows/{{.WORKFLOW_ID}}_bundled.cwl
    - |
      uv run --no-cache --no-project --with cwl2puml cwl2puml --workflow-id {{.WORKFLOW_ID}} \
        --output {{.DOC_DIR}}/{{.WORKFLOW_ID}} \
        --convert-image \
        --image-format svg \
        ./cwl-workflows/{{.WORKFLOW_ID}}_bundled.cwl
    - rm -rf {{.DOC_DIR}}/{{.WORKFLOW_ID}}/*.puml

  generate_workflows_doc:
    desc: Generate markdown and workflow diagrams for FEM, FFM and FHM CWL workflow
    vars:
      WORKFLOWS:
      - 'publish_workflow'
      - 'publish_experiment_products'
    cmds:
    - for:
        var: WORKFLOWS
        as: WORKFLOW_ID
      task: generate_workflow_doc
      vars:
        WORKFLOW_ID: '{{.WORKFLOW_ID}}'

  publish_workflow:
    desc: Invoke the bundled publish_workflow CWL workflow
    requires:
      vars:
      - WORKFLOW_ID
      - PROJECT_ID
      - PROJECT_NAME
      - OGC_API_PROCESSES_ENDPOINT
      - CWL_WORKFLOW_LOCATION
    cmds:
    - task: bundle_worflow
      vars:
        WORKFLOW_ID: "publish_workflow"
    - |
      set -eu

      set -a
      . ./cwl-workflows/.env
      set +a

      job_order="$(mktemp --suffix=.json publish_workflow.XXXXXXX)"
      trap 'rm -f "$job_order"' EXIT

      jq -n \
      --arg workflow_id {{shellQuote .WORKFLOW_ID}} \
      --arg project_id {{shellQuote .PROJECT_ID}} \
      --arg project_name {{shellQuote .PROJECT_NAME}} \
      --arg ogc_api_processes_endpoint {{shellQuote .OGC_API_PROCESSES_ENDPOINT}} \
      --arg cwl_workflow_location {{shellQuote .CWL_WORKFLOW_LOCATION}} \
      '{
        workflow_id: $workflow_id,
        project_id: $project_id,
        project_name: $project_name,
        ogc_api_processes_endpoint: {
          value: $ogc_api_processes_endpoint
        },
        cwl_workflow_location: {
          value: $cwl_workflow_location
        }
      }' > "$job_order"

      uv run \
      --no-cache \
      --no-project \
      --with cwltool \
      cwltool \
      --preserve-environment REPOSITORY_PATH \
      --preserve-environment REPOSITORY_URL \
      --preserve-environment BRANCH \
      --preserve-environment REMOTE \
      ./cwl-workflows/publish_workflow_bundled.cwl#publish_workflow \
      "$job_order"

  publish_experiment_products:
    desc: Invoke the bundled publish_experiment_products CWL workflow
    requires:
      vars:
      - JOB_ID
      - PROJECT_ID
      - PROJECT_NAME
      - OGC_API_PROCESSES_ENDPOINT
      - CWL_WORKFLOW_LOCATION
      - WORKFLOW_ID
      - AUTHORIZATION_TOKEN
    cmds:
    - task: bundle_worflow
      vars:
        WORKFLOW_ID: "publish_experiment_products"
    - |
      set -eu

      set -a
      . ./cwl-workflows/.env
      set +a

      job_order="$(mktemp --suffix=.json publish_experiment_products.XXXXXXX)"
      trap 'rm -f "$job_order"' EXIT

      jq -n \
      --arg job_id {{shellQuote .JOB_ID}} \
      --arg project_id {{shellQuote .PROJECT_ID}} \
      --arg project_name {{shellQuote .PROJECT_NAME}} \
      --arg ogc_api_processes_endpoint {{shellQuote .OGC_API_PROCESSES_ENDPOINT}} \
      --arg cwl_workflow_location {{shellQuote .CWL_WORKFLOW_LOCATION}} \
      --arg workflow_id {{shellQuote .WORKFLOW_ID}} \
      --arg authorization_token {{shellQuote .AUTHORIZATION_TOKEN}} \
      '{
        job_id: $job_id,
        project_id: $project_id,
        project_name: $project_name,
        ogc_api_processes_endpoint: {
          value: $ogc_api_processes_endpoint
        },
        cwl_workflow_location: {
          value: $cwl_workflow_location
        },
        workflow_id: $workflow_id,
        authorization_token: $authorization_token
      }' > "$job_order"

      uv run \
      --no-cache \
      --no-project \
      --with cwltool \
      cwltool \
      --preserve-environment REPOSITORY_PATH \
      --preserve-environment REPOSITORY_URL \
      --preserve-environment BRANCH \
      --preserve-environment REMOTE \
      ./cwl-workflows/publish_experiment_products_bundled.cwl#publish_experiment_products \
      "$job_order"

  serve_docs:
    desc: Serve the MkDocs site locally
    cmds:
      - |
        uv run \
        --no-project \
        --with mkdocs \
        --with mkdocs-material \
        --with mkdocs-mermaid2-plugin \
        --with mkdocs-build-plantuml-plugin \
        mkdocs serve
