# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  osc_ogcapi_records_models.yaml
#   timestamp: 2026-03-26T09:49:14+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import Field, RootModel
from transpiler_mate.ogcapi.records.ogcapi_records_models import RecordCommonProperties


class Model(RootModel[Any]):
    root: Any


class OscStatus(Enum):
    PLANNED = "planned"
    ONGOING = "ongoing"
    COMPLETED = "completed"


class WorkflowProperties(RecordCommonProperties):
    osc_type: Optional[str] = Field("workflow", alias="osc:type")
    osc_project: Optional[str] = Field(None, alias="osc:project")
    osc_status: Optional[OscStatus] = Field(None, alias="osc:status")


class ExperimentProperties(RecordCommonProperties):
    osc_project: Optional[str] = Field(None, alias="osc:project")
    osc_workflow: Optional[str] = Field(None, alias="osc:workflow")
    osc_prov_generated_by: Optional[str] = Field(None, alias="osc-prov:generatedBy")
    osc_prov_started_at_time: Optional[datetime] = Field(
        None, alias="osc-prov:startedAtTime"
    )
    osc_prov_ended_at_time: Optional[datetime] = Field(
        None, alias="osc-prov:endedAtTime"
    )
    osc_prov_generated: Optional[str] = Field(None, alias="osc-prov:generated")
    osc_prov_described_by_workflow: Optional[str] = Field(
        None, alias="osc-prov:describedByWorkflow"
    )


class ProductProperties(RecordCommonProperties):
    osc_experiment: Optional[str] = Field(None, alias="osc:experiment")
    osc_status: Optional[str] = Field(None, alias="osc:status")
    osc_region: Optional[str] = Field(None, alias="osc:region")
    osc_type: Optional[str] = Field(None, alias="osc:type")
    osc_project: Optional[str] = Field(None, alias="osc:project")
    osc_missions: Optional[str] = Field(None, alias="osc:missions")
    osc_variables: Optional[str] = Field(None, alias="osc:variables")
    osc_prov_type: Optional[str] = Field(None, alias="osc-prov:type")
    osc_prov_was_derived_from: Optional[str] = Field(
        None, alias="osc-prov:wasDerivedFrom"
    )
    osc_prov_was_output_from: Optional[str] = Field(
        None, alias="osc-prov:wasOutputFrom"
    )
    osc_prov_described_by_parameter: Optional[str] = Field(
        None, alias="osc-prov:describedByParameter"
    )
